google/certificate-transparency-rfcs

rfc6962-bis.xml
And how TLS clients could check whether a domain name in a precertificate is overly redacted.
=> Ticket 42: Clarify overly-redacted

rfc6962-bis.xml
Require logs to accept certificates that meet a well-defined validity criteria.
This should address Steve Kent's concern about variation in logs' behaviour.
By requiring that logs accept certificates that are valid according to
X.509's validity requirement, a submitter can be certain their certificates
will be accepted.
=> Ticket 21: Specify cert acceptance criteria.

rfc6962-bis.xml
Stand-alone auditing isn't likely to happen. Instead, each of
the clients mentioned can take on the additional responsibility of auditing.
Re-word to clarify what are the auditing aspects of each client and include
them in the section for each client (if not already there).
=> Ticket 40: Clarify auditing

rfc6962-bis.xml
Rather than specify exactly what a monitor could be doing in addition to log monitoring, give an example.
=> Ticket 39: Potential monitor behaviour.

rfc6962-bis.xml
(1) Remove debugging API.
(2) Make the second parameter of get-sth-consistency explicitly optional.
=> Remove debugging API, make parameter optional

rfc6962-bis.xml
The `LogEntryType` enum is used in a number of places, but the `LogEntry`
structure is never used anywhere.  I remember this causing me no end of
confusion when I was grappling with understanding RFC6962, and since the
structure hasn't seen any new use since, I'm thinking it can probably stand
to go.
=> Remove unreferenced LogEntry structure

rfc6962-bis.xml
First one was an outdent issue, second was some spurious tabs inside of an artwork block.
=> Fix minor spacing issues that were causing xml2rfc warnings.

rfc6962-bis.xml
The example using v1 get-entries is bad as a v1 log is unlikely to return the
error codes described in bis.
add-pre-chain requires a version upgrade as it's specified to return the same
outputs as add-chain, which now returns the SCT in binary format.
get-sth may need updating as well since entries are structured differently.
=> Correct versioning of some calls.

rfc6962-bis.xml
Since logs SHOULD limit the length of chains accepted, that value should be
known to clients in advance.
=> Add the maximum chain length to the log metadata.

rfc6962-bis.xml
This spec focuses on CA-issued X.509 certificates, so calling for suggestions
for DANE and self-signed certificates is irrelevant.
=> Remove mentioning of DANE and self-signed certificates.

rfc6962-bis.xml
A log's size may remain constant (in case it is frozen) or increase (in case
of normal operation). Hopefully that better describes it.
=> Describe a log is extensible, not necessarily ever-growing.

rfc6962-bis.xml
The RFC should specify how to determine whether a certificate is CT-compliant
or not, by specifying the requirement for SCTs to be present alongside it
during the TLS handshake and how to check their validity.
Once the compliance status of the certificate has been established, it is
up to the client to decide how it behaves.
This commit attempts to reflect that.
=> Bashing more client behaviour statements.

rfc6962-bis.xml
The Log Format and Operation section should describe just that.  This PR moves requirements for other parties (Submitters, CAs, TLS servers and TLS clients) into more appropriate sections.
=> Reorganize requirements into appropriate sections

rfc6962-bis.xml
That yields a valid DER-encoded ASN.1 OID by prepending the tag 0x06 to
the LogID bytes.
=> Change the LogID length to fit into one byte.

rfc6962-bis.xml, test_rfc_algorithms.py
Without checking sn, the same proof would be accepted for multiple tree sizes.
Thanks to David Benjamin for finding this out.
=> Fix the consistency checking proof to account for sizes.

rfc6962-bis.xml
Add definition of precertificate before use in section 3. Not renaming all usage to pre-certificates as this hasapparently been discussed before.
=> Address trac issue 138.

rfc6962-bis.xml
I don't think we should leave the wording as is as it implies the list of ways to misbehave has been fully
enumerated in this document. My suggestion is to make these examples and link to the threat analysis.
=> Address issue 133. 

rfc6962-bis.xml
The added text should make it clear why supporting algorithm agility (in practice, allowing logs to support multiple signature and hash algorithms) is too complex and unnecessary given the simpler alternative of freezing a log.
=> Ticket 78: More text about algorithm agility

rfc6962-bis.xml
This has been renamed to Merkle inclusion proof.
=> Remove an instance of outdated term 'Merkle audit proof'.

rfc6962-bis.xml
It should be clear that certificate submission is not limited to one
entity in the protocol. Whether submitted certificates are accepted
by a log or not is up to the log's policy.
=> Ticket 120: Clarify this is about the protocol.

rfc6962-bis.xml
Add documentation of what the boolean parameter to SUBPROOF represents and
link it to subproof definition description.  Intention is to make understanding the Merkle Consistency Proofs section more understandable.
=> Merkle Consistency Proofs description clarity

rfc6962-bis.xml
Remove the vague terminology 'partial information' in section 'Auditing'. Flesh out descriptions of the duties of auditing via STH and auditing via SCT.
=> Ticket 141 auditing description

rfc6962-bis.xml
Per dkg's request, describing what a responsible log shutdown
should look like by suggesting several actions to take.
=> Ticket 109: Describing log shutdown.

rfc6962-bis.xml
Text from section 12.6 "Multiple SCTs" is moved into section 7 where Multiple SCTs are first discussed.  The former section 12.6 is retained with a reference back to sect. 7.
=> Ticket 143:  re-organization of sections related to Multiple SCTs.

rfc6962-bis.xml
Both for TLS servers and clients. Since it is not extensively implemented, it should only be an optional additional mechanism for now.
Addressing [ticket 112](https://tools.ietf.org/wg/trans/trac/ticket/112).
=> Add mentions of the status_request_v2 extension.

rfc6962-bis.xml, test_rfc_algorithms.py
- Make 'opensource' inclusion-proof-checking function more closely resemble
the actual opensource inclusion-proof-checking function
- Add more thorough testing of RFC algorithm for verifying inclusion
proofs
- Fix incorrect results when leaf_index >= tree_size
- Fix incorrect results when tree height is too large
- Reflect these fixes in the RFC
=> Ticket 115: Verifying inclusion proofs

rfc6962-bis.xml
Some modifications to the redaction text as well as indication that redacted wildcards are not allowed.
Commits are separate to ease review, will squash when (if!) they are accepted.
=> Ticket 57: Redacted wildcards should not be allowed

rfc6962-bis.xml
To limit the log's ability of fingerprinting clients.
=> Indicate logs SHOULD reuse SCTs.

rfc6962-bis.xml
Clarify that rejection of an SCT means treating it as non-valid.
=> Language change around SCTs with timestamp in the future.

rfc6962-bis.xml
Suggest evaluating the certificates in the order they were sent by the TLS server.
Clarify that TLS clients MUST NOT consider invalid any SCT or inclusion proof until each potentially corresponding certificate has been evaluated.
=> Ticket 155: Describe how to match SCTs to certificates.

rfc6962-bis.xml
See http://trac.tools.ietf.org/wg/trans/trac/ticket/142 for the reasoning behind this.
=> Ticket 142: Specify clients should send an empty extension_data.

rfc6962-bis.xml
V1 and V2 SCTs can co-exist for X.509 certificates, but not precertificates.
I've briefly explored the option of allowing V2 SCTs to be valid for V1 precerts
by specifying that V2 clients should remove the X.509 extension with V1 SCTs
prior to checking V2 SCT signatures.
However it is unclear the complication is worth it as V1 clients will not
be able to use V2 SCTs, so the benefit is unclear.
=> Ticket 153: Explain V1/V2 interoperability.

rfc6962-bis.xml
Clarify that monitors may watch logs to audit their behaviour, for certificates
of interest or both.
=> Ticket 118: Monitors may do one of several things.

rfc6962-bis.xml
Adopting David's suggestion to recommend that a TLS server inspects the
set of logs acceptable/recognized by popular TLS clients.
=> Ticket 131: Provide guidance on selecting CT logs.

rfc6962-bis.xml
Incorporate some of the comments in ticket 141, describing what aspects of log
behaviour should be audited.
Note that while some are described in the auditing section, others are
in the security considerations section.
=> Ticket 141: Further expand auditing

rfc6962-bis.xml
…proofs.
The gist of the reasoning is that without the timestamp and extensions fields
from the SCT, it is not possible to calculate the leaf hash that would
be used together with the rest of the nodes from the inclusion proof to
calculate the root hash.
To make implementation of clients simpler (i.e. clients would only need
to check signatures from SCTs rather than having to check them over STHs
as well and implement inclusion checking) this PR suggests mandating
presence of SCTs, while pointing out the benefit of supplying both
SCT and inclusion proof.
=> Ticket 156: Requiring SCTs in addition to inclusion proofs

rfc6962-bis.xml
Try running "xml2rfc --html" without this fix.  The "Reconstructing the TBSCertificate" section looks very odd!
=> Fix formatting.

rfc6962-bis.xml
The "item_extensions" field was removed in https://github.com/google/certificate-transparency-rfcs/commit/d71d7707a3eeb5707cf5048c3849b068e477038c
=> Remove stray references to item_extensions.

rfc6962-bis.xml
Attempting to clarify that, because the timestamp in the SCT is a part of the leaf data (it's in TimestampedCertificateEntryDataV2) and, because we use deterministic signatures, different SCTs for the same submission (which imply different timestamps) must be incorporated into the tree independently and there should be a log entry for each.
It is not enough to only incorporate one submission + SCT, since clients that will observe other SCTs will reconstruct a different TimestampedCertificateEntryDataV2 than the one in the log, and so will have a leaf hash for which the log can't prove inclusion.
=> There should be exactly one SCT for each entry.

rfc6962-bis.xml
[O] to one or more logs, however certificate
[P] to one or more logs; however, certificate
[R] Grammar/run on sentence
No formatting change. Original line: 125 words, 742 characters.
Long lines make github diff sad.
=> Grammar nit.

rfc6962-bis.xml
O: "Each log consists of certificate chains, which can be submitted by anyone. "
P: "Each log contains certificate chains, which can be submitted by anyone. "
C: s/consists of/contains/ - very much optional, but "consists of"
sounds more like the log is *just* certificate chains, and nothing
else.
I'm happy to sometime go through and shorten all the lines so that github diff works, but this will be a big change / may make history tricky...
=> Clarity - "consists of" -> "contains"

rfc6962-bis.xml
Change behaviour to require that if a log accepts a submission it must issue an SCT, but it may reject it with "bad certificate" if it detects bad encoding.
Reasoning:
* get-entries specifies that each entry returned is accompanied by an SCT.
* Without an SCT for each entry, the client is forced to identify the encoding error, to figure out if it's justified that the log did not supply an SCT.
* Given that not all SSL software can identify encoding errors, it may be best to leave it to monitors to scrutinize each entry and allow logs to treat these submissions, if they can process them (and choose to) to treat them like regular entries. Right now there's no provisioning in the tree-related data structure to single out "badly encoded" entries, so in essence a timestamp will have to be …
=> Logs must issue SCTs for all accepted submissions

rfc6962-bis.xml
* Clarify which STH is being referred to by get-all-by-sth.
* Recommend providing the final STH as a TransItem.
* Note the Transparency Information extension should be removed when
reconstructing the TBSCertificate.
=> Addressing coments from Andrew Ayer:

rfc6962-bis.xml
"may" sounds permissive, "might" sounds better; otherwise this sounds like a permission and not a prediction.
Alternatively, the proposed text...
=> Section 3.1: Clarify the "may" is not permissive.

rfc6962-bis.xml
CAs do not have to include the  subjectAltName extension (this is a BR). Indicate that the subjectAltName extension may be omitted even if it's to be included in the final certificate.
Also, clarify that logs MUST reject a submission where both the subjectAltName and redactedSAN extensions are present, since they make no sense.
=> The subjectAltName extension is optional.

rfc6962-bis.xml
Saying that || denotes length-encoded concatenation would apply length-encoding
to the result of LABELHASH and the result of BASE32 (as concatenation is used
3 times in the REDACT function), but length encoding is only necessary for
the values that are being hashed.
=> Bugfix: Only prefix hashed values with length

rfc6962-bis.xml
Be clear that:
- Only dNSName identities can be redacted using the first redaction mechanism.
- The second redaction mechanism (name-constrained intermediate CA cert) allows redaction of dNSName and any other field in the subjectAltName.
=> Be explicit about what can be redacted and how.

rfc6962-bis.xml
Addressing James Manger's comment that "this limitation needs to be stated clearly":
https://mailarchive.ietf.org/arch/msg/trans/oC3wkUncgHP1LI3zkoerMzCB7n8
=> Effective redaction requires labels to have sufficient entropy

rfc6962-bis.xml
See https://trac.tools.ietf.org/wg/trans/trac/ticket/158 on why it's inconvenient to have fixed-length fields specified in the various data structures when the length depends on the log the data is parsed from.
This PR also allows more space for nodes in proofs, covering PR #187.
=> Ticket 158: Make NodeHash variable-length

rfc6962-bis.xml
That makes life simpler for clients by not requiring them to re-encode the STH fields in order to validate the signature.
=> STH: Signature over TreeHeadDataV2 rather than TransItem.

Makefile, dns/Makefile, redaction/Makefile
It seems that the xml2rfc tools server was recently relocated, but kramdown-rfc2629 can't cope with the redirection.  This PR implements a (hopefully temporary) workaround.
.refcache/reference.RFC.2119.xml: fetching
/usr/lib64/ruby/2.1.0/open-uri.rb:223:in `open_loop': redirection forbidden: http://xml2rfc.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml -> https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.2119.xml (RuntimeError)
from /usr/lib64/ruby/2.1.0/open-uri.rb:149:in `open_uri'
from /usr/lib64/ruby/2.1.0/open-uri.rb:704:in `open'
from /usr/lib64/ruby/2.1.0/open-uri.rb:34:in `open'
from /home/rob/.gem/ruby/2.1.0/gems/kramdown-rfc2629-1.0.33/lib/kramdown-rfc2629.rb:436:in `block in get_and_cache_resource'
from /usr/lib64/ruby/2.1.0/timeout.rb:90:in `block in timeout' …
=> Workaround xml2rfc breakage.

draft-ietf-trans-rfc6962-bis.md
Per discussion at the trans workgroup today, rather than significantly re-work this section and go through WGLC again, simply relax acceptance criteria of submissions into logs by changing MUST to a SHOULD.
=> Amend section 5.1: Log acceptance criteria.

draft-ietf-trans-rfc6962-bis.md
The optional methods removed in this PR have been moved to the monitoring API in PR #203.
=> Remove optional API.

how-to-push-i-d.txt
The instructions are different since the move to markdown.
Note that compared to the XML file, where the *next* version number was always kept, the markdown version has the *current* version number and so has to be bumped first, before uploading an i-d.
=> Updating 'how to push i-d' instructions.

draft-ietf-trans-rfc6962-bis.md
Specify the policy for adding values to the various IANA registries
required in 6962-bis.
A specification is required for all registries, except Log IDs.
Log IDs are handed on a "First Come First Serve" basis.
Both policies are defined in RFC5226, so a reference to it has been added.
=> Specify policy for IANA registries.

draft-ietf-trans-rfc6962-bis.md
This PR doesn't add a registry, but makes clear why one isn't necessary.  In particular, there is explicitly no extensibility for reusable error codes.
=> Issue #186 - Add a registry for error codes

draft-ietf-trans-rfc6962-bis.md
When get-consistency-proof is called with identical `first`, `second`, then the returned consistency proof should be empty.
=> Ticket 188: Empty consistency proof for equal tree sizes.

draft-ietf-trans-rfc6962-bis.md
To avoid policy discussions in an RFC:
* Indicate that log operators should not impose conditions on accessing
the log, but do not require it strongly (this requirement is not
essential to the operation of the protocol).
* Clarify exactly what are logs expected to accept for spam mitigation
(this is needed to guarantee that log clients find what they expect in
the log).
=> Issue 165: Clarify operational restrictions on logs

draft-ietf-trans-rfc6962-bis.md
Use a slightly more standard notation to define:
* The tree: D_n
* Nodes in the tree: D[k]
* Derivation of one tree from the other.
Credit to Richard Barnes and Ben Laurie for suggesting the
improved syntax.
=> Issue #182 - Clarify notation in the Merkle tree section

draft-ietf-trans-rfc6962-bis.md
Define what it means to incorporate a submission into the tree.
Additionally, clarify what a log MUST do to adhere with this
requirement:
Rather than dictate that this is done periodically, state it MUST
be done within the MMD for each submission, pointing out that batching
of the operation as an implementation detail.
=> Issue 167: Defining incorporation

draft-ietf-trans-rfc6962-bis.md
Per discussion on trans, making deterministic signing optional,
mentioning that deterministic signing can be achieved by storing
the signature blobs rather than re-signing the same SCTs for
the same submissions.
=> Remove deterministic signatures requirement

draft-ietf-trans-rfc6962-bis.md
This PR incorporates and is intended to replace PRs #238 and #248.  As per discussion on the list...
* the consolidated endpoint is now called "submit-entry" (rather than "add-entry").
* there's now only one parameter ("submission") that carries the submitted certificate or precertificate.
I've also updated the parameter descriptions and error messages accordingly.
=> Issue #181 - Consolidate 'add-chain' and 'add-pre-chain'

draft-ietf-trans-rfc6962-bis.md
Detail the TransItem that has to be constructed as the input to the
signature validation phase, when validating SCTs.
=> Issue #178: Describe how to validate an SCT

draft-ietf-trans-rfc6962-bis.md
Remove repeated text about TLS clients having to validate inclusion
proofs.
Make it clear they SHOULD do it, though.
=> Issue #164: Clarify roles of TLS clients.

draft-ietf-trans-rfc6962-bis.md
Clarify that it make take up to twice the MMD for a submission
to be available to log monitors, since a submission must be
incorporated within the MMD, but an old STH may be served so
the incorporated entry may not be available until the STH that
includes it is served.
=> Issue 175: Clarifying guarantees around MMD, STH age.

draft-ietf-trans-rfc6962-bis.md
These structures are not needed if the value returned by get-entries is the original submission JSON, which will be easier for clients to parse anyway.
=> Removing X509ChainEntry/PrecertChainEntryV2

draft-ietf-trans-rfc6962-bis.md
Explain how a precertificate signature cannot be a certificate signature.
Draw attention to the RFC5652 requirement to include the 'signedAttrs' field.
=> Issue #79 revisited - Precertificate signature must be over something other than just the TBSCertificate

draft-ietf-trans-rfc6962-bis.md
This is in place of PR #241, removing text and adding as little as possible to clarify embedded inclusion proofs are another way to achieve compliance.
=> Issue 184: Clarify CT compliance checking.

draft-ietf-trans-rfc6962-bis.md
* Use the right output parameter name.
* Mention replacement of add-chain / add-pre-chain with submit-entry.
=> Small editorial fixes

draft-ietf-trans-rfc6962-bis.md
Mention mutation of certificate signatures as a log misbehaviour.
=> Clarify that non-self-signed trust anchors cannot be submitted to submit-entry.

draft-ietf-trans-rfc6962-bis.md
This PR, which replace #289, incorporates Eran's text from #293 with Al's and my comments.  I'm going to merge it without waiting for the usual approvals, in order to get an updated I-D submitted before today's I-D submission deadline.
=> Clarify why submissions must chain to an accepted trust anchor.

draft-ietf-trans-rfc6962-bis.md
Implement the changes suggested by Andrew Ayer in this message to the TRANS list:
https://mailarchive.ietf.org/arch/msg/trans/wNYK7FNbWDNqoTpPO0u1HsJOpSc
=> A-D review: Remove the 'no security implications' claim

draft-ietf-trans-rfc6962-bis.md
As per discussion with the TRANS Chairs, Security A-Ds, and the other 6962-bis authors.
=> Switch intended status of 6962-bis from Standards Track to Experimental.

draft-ietf-trans-rfc6962-bis.md
The TLS 1.3 RFC has now been published (RFC8446).
We were previously referencing the TLS 1.2 RFC and a draft version of TLS 1.3.  This PR switches to just referencing the TLS 1.3 RFC, and it also clarifies the IANA Considerations regarding the request to add the transparency_info TLS extension to the TLS ExtensionType Values registry (see https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml for IANA's view of this registry).
=> Reference (only) the TLS 1.3 RFC.

draft-ietf-trans-rfc6962-bis.md
As pointed out on the trans mailing list, the definition of the
timestamp in the document conflated NTP time and Unix time, see:
https://mailarchive.ietf.org/arch/msg/trans/wwQYt2vsKOGIHqfSipJXHd2-okI
Make it clear that Unix time is actually used in the timestamps.
=> Changing NTP time to Unix time

draft-ietf-trans-rfc6962-bis.md
This PR addresses the issues with https://www.ietf.org/id/draft-ietf-trans-rfc6962-bis-29.txt found by https://tools.ietf.org/tools/idnits/.  Here is the idnits output, with comments inline...
```
idnits 2.16.0 
tmp/draft-ietf-trans-rfc6962-bis-29.txt:
tmp/draft-ietf-trans-rfc6962-bis-29.txt(380): Unexpected reference format: '...  {d'[0] = d[...'
tmp/draft-ietf-trans-rfc6962-bis-29.txt(465): Unexpected reference format: '...0, {d[0]}) = ...'
```
Nothing to fix.  It seems unlikely that readers of this document will think that these [ ] brackets denote references.
```
tmp/draft-ietf-trans-rfc6962-bis-29.txt(775): Found possible IPv4 address '1.3.101.78' in position 41; this doesn't match the suggested documentation address ranges specified in RFC 6890 (or successor): blocks 192.0.2.0/24 …
```
=> Fix idnits in -29

draft-ietf-trans-rfc6962-bis.md
We dropped support for status_request_v2 in https://github.com/google/certificate-transparency-rfcs/commit/e9b69e5d580fddd5860707a2cbe26004ceb58e57, but missed this mention of it in the "Major Differences from CT 1.0" section.
=> Remove stray reference to status_request_v2.

draft-ietf-trans-rfc6962-bis.md
This PR proposes to split the "Accepting Submissions" section into two subsections, in order to clarify what are the minimum rules and what's left to the log's discretion.
It also enumerates the minimum rules.
=> A-D Review: Clarify submission acceptance rules.

draft-ietf-trans-rfc6962-bis.md
Per discussion on the TLS/TRANS mailing lists, this PR drops the option to use cached-info (RFC7924), which we had previously added in https://github.com/google/certificate-transparency-rfcs/pull/186 (see also https://trac.ietf.org/trac/trans/ticket/111).
=> Drop the use of cached_info.

draft-ietf-trans-rfc6962-bis.md
The 6962-bis authors received this comment:
> In page 9 of https://tools.ietf.org/html/draft-ietf-trans-rfc6962-bis-31 in section in section 2.1.3.1. we find
> The : operator and D[k1:k2] are defined the same as in Section 2.1.1.
> However, in section 2.1.1. the operator : is not found. There is no definition of this operator.
RFC6962 section 2.1.1 defined the colon operator as:
> where : is concatenation of lists
This PR restores this definition, by adding it to section 2.1.1.
=> Explicitly define the colon operator.

draft-ietf-trans-rfc6962-bis.md
> On 13th March 2019, Alissa Cooper wrote:
> Glad to see this revision of the protocol. My comments and questions should be easy to address.
> 
> = Section 10.2, 10.4, 10.5 =
> 
> A Specification Required registry policy implies expert review. So a registry policy of "Specification Required and Expert Review" is duplicative; it should just say "Specification Required." I know this seems trivial but there has been so much confusion about this through the years that it is important to be precise.
Addressed by https://github.com/robstradling/certificate-transparency-rfcs/commit/0a21e8c769bc8d5c0d28bb4c610175476187478a
> = Section 10.3 =
> 
> This section needs to state what the registry policy is for the code points not already registered (presumably Expert Review given 10.3.1, but it needs …
=> IESG Last Call: Address Alissa Cooper's DISCUSS and COMMENT feedback

draft-ietf-trans-rfc6962-bis.md
> On 13th March 2019, Adam Roach wrote:
> Thanks to everyone who worked on updating this protocol to reflect experience
> gathered from the initial CT protocol. I have one blocking comment, and a small
> number of editorial suggestions.
> 
> ---------------------------------------------------------------------------
> 
> §5:
> 
> >  Clients are configured with a base URL for a log and construct URLs
> >  for requests by appending suffixes to this base URL.  This structure
> >  places some degree of restriction on how log operators can deploy
> >  these services, as noted in [RFC7320].  However, operational
> >  experience with version 1 of this protocol has not indicated that
> >  these restrictions are a problem in practice.
> 
> The synthesis of URLs by a protocol in this fashion is …
=> IESG Last Call: Address Adam Roach's DISCUSS and COMMENT feedback

draft-ietf-trans-rfc6962-bis.md
Following recent discussion on the ART list, BCP190 is being revised:
https://datatracker.ietf.org/doc/draft-nottingham-rfc7320bis/
7320-bis relaxes the BCP190 requirements that affected 6962-bis.  Although 7320-bis is still being drafted, we have received approval to revert the (unpopular) BCP190-compliance changes that were introduced in PR #310.
This PR reverts https://github.com/google/certificate-transparency-rfcs/commit/84998e6cb8ca5bd2c1c001b95ffdff7b0d63bb23 and https://github.com/google/certificate-transparency-rfcs/commit/aa274ed6246bb99eab5b35c6a0cf55ec42ebfe72.
=> IESG Last Call: BCP 190 compliance revisited

draft-ietf-trans-rfc6962-bis.md
This PR addresses feedback on the TRANS list from James @manger:
https://mailarchive.ietf.org/arch/msg/trans/jT9CajEdKQB3R9BdozYTYfceIyw
=> Clarify Base URL properties, and use <Base URL> instead of <log server> to define the client message URLs.

draft-ietf-trans-rfc6962-bis.md
Issuing a precertificate signals the CA's binding intent to issue the corresponding certificate.  Experience with CTv1 and recent discussions on the TRANS and mozilla.dev.security.policy lists have shown that some of the implications of this are not obvious, and so this PR attempts to clarify some of these implications.
=> Clarify some implications of the binding intent to issue.

draft-ietf-trans-rfc6962-bis.md
> There was a presentation at maprg IETF 103 about the question if CT helps
> attackers to find new domains. I think this risk should at least be mentioned
> in the security considerations section.
Addressed by https://github.com/robstradling/certificate-transparency-rfcs/commit/3b2ec0a51f8abb4c8c0b985614fefa4291432dd9
>   1) I found section 2 a bit hard to follow. Would it maybe be possible to
>   provide more textual explanation of the algorithms instead of just describing
>   the steps of the algorithms? Also I was wondering how much much these
>   algorithms are actually „part“ of the protocol spec…? Are could these be
>   rather seen as example algorithms? Maybe that could be further clarified
We'll consider these comments on section 2 at a later date, along with Benjamin Kaduk's …
=> IEST Last Call: Address Mirja Kühlewind's DISCUSS and COMMENT feedback

draft-ietf-trans-rfc6962-bis.md
Explain why server-side isn't discussed.  I.e., non-use of CT for TLS client certificates.
=> Add section on TLS server

draft-ietf-trans-rfc6962-bis.md
Three ways for a server to send CT data. Clarify when and how each is used.
=> Clarify server status options

draft-ietf-trans-rfc6962-bis.md
This addresses the comments Mirja had during IESG review.  No changes were made for the following:
```
7) sec 10.3: Couldn’t you use the TLS  SignatureScheme Registry directly (instead of forming an own registry)?
8) sec 10.4: i Wonder if an RFC-required policy wouldn’t be more appropriate for the VersionedTransTypes registry?
9) sec 10.6.1:I guess  the registration policy is FCFS? RFC 8126 recommend to always (clearly) name the registry.
And finally one higher level question mainly out of curiosity: was it considered to e.g. use json for all data structures? Is there a performance reason to not do that or wasn’t that even discussed?
```
Replies:
7 Using the TLS registry is not appropriate, the signatures are for different protocols even though the algorithm is the same
8 No.
9. OID's are …
=> Mirja comments

draft-ietf-trans-rfc6962-bis.md
Ben Kaduk pointed out that the `ConsistencyProofDataV2` and `InclusionProofDataV2` had arrays that could not be empty. This was contradicted elsewhere in the document, so fix the `1..` to `0..` in both cases.
This should address the last part of Ben's DISCUSS.
=> Proof paths can be zero-length

draft-ietf-trans-rfc6962-bis.md
Since the threat-analysis draft is also dead, remove references to it.
=> Remove refs to draft-ietf-trans-threat-analysis

draft-ietf-trans-rfc6962-bis.md
This is the only idnit that seems to need addressing in -36.
See https://www6.ietf.org/tools/idnits?url=https://www.ietf.org/archive/id/draft-ietf-trans-rfc6962-bis-36.txt
=> RFC7320 is obsoleted by RFC8820.

draft-ietf-trans-rfc6962-bis.md
Move the OId text up, and out of the IANA section.
Add clarification that a new "Certificate Transparency" protocol
registry is being created, and six registries within it.
=> Clarify IANA actions (Murray's feedback)

draft-ietf-trans-rfc6962-bis.md
=> Remove 'Registry' from Log ID registry name

draft-ietf-trans-rfc6962-bis.md
Mostly minor stuff, markdown and grammar nits and the like.
The one (?) exception is changing the presentation language for an `opaque signature<>` entry to have a minimum length of 1 instead of 0.  There are two `opaque signature<>` elements in the document, and the other one already had this change applied due to a previous review of mine, so I claim it still is effectively "minor".
=> Editorial suggestions from Benjamin Kaduk's IESG review

draft-ietf-trans-rfc6962-bis.md
Make sure it's spelled out the first time it's used.
Use acronym in section title except for the definition and include
the acronym then.
=> Be consistent in SCT/STH acronym use

draft-ietf-trans-rfc6962-bis.md
This PR aligns our "IETF URN Sub-namespace for Registered Protocol Parameter Identifiers" registration with the approach taken by ACME (RFC8555), which was our original intent.
Although 6962-bis only uses `trans:error`, it's possible that future extensions might want to use `trans:<something_else>`.
=> Register entire TRANS namespace, not just trans:error.
