google/certificate-transparency-rfcs

how-to-push-i-d.txt
=> Instructions on pushing a new I-D.

how-to-push-i-d.txt
=> Add version bump.

Makefile, rfc6962-bis.xml
=> Close http://trac.tools.ietf.org/wg/trans/trac/ticket/35.

rfc6962-bis.xml
=> Explain why there are three SCT delivery mechanisms.

rfc6962-bis.xml
http://trac.tools.ietf.org/wg/trans/trac/ticket/28
@eranmes
=> Specify how to change algorithms.

rfc6962-bis.xml
http://trac.tools.ietf.org/wg/trans/trac/ticket/33
@eranmes
=> Return the max chain length.

rfc6962-bis.xml
=> Make layout consistent.

rfc6962-bis.xml
=> Move normative references to the correct section.

rfc6962-bis.xml
TRAC [ticket 4](http://trac.tools.ietf.org/wg/trans/trac/ticket/4).
=> Sign TBSCertificate (rather than ASN.1Cert) for X509ChainEntry entries.

rfc6962-bis.xml
=> Switch to using encoded SCT. Some version and wording cleanup.

rfc6962-bis.xml
(and this is my first RFC pull request so please go easy!)
=> Be explicit about which output parameters are included in the signature and which are not

rfc6962-bis.xml, test_rfc_algorithms.py
Some other misc spacing changes to remove warnings from xml2rfc tool.
=> Add algorithms for verifying inclusion proofs, consistency checks

rfc6962-bis.xml
=> Tidy artwork

dns/Makefile, dns/draft-ct-over-dns.md, test_rfc_algorithms.py
It's possibly not quite in a great condition to check-in, but I may be out for a few days so wanted to get something out.
=> Initial check-in for ID for DNS

dns/draft-ct-over-dns.md
@pphaneuf  Please take a look.
=> First cut at adding ".sth" and ".sth-consistency" docs for DNS.

rfc6962-bis.xml
Similar to how hash algorithms are specified.
=> Ticket 64: Remove specification of signature algorithms.

rfc6962-bis.xml
=> Don't call logs "untrusted".

rfc6962-bis.xml
=> Efficiency is dealt with throughout the I-D - get rid of not particularly useful section on it.

rfc6962-bis.xml
Add reference to it from section 'Clients'.
See https://trac.tools.ietf.org/wg/trans/trac/ticket/87
=> Ticket: 87 - Add informative reference for CT Threat Analysis

rfc6962-bis.xml
=> Only mention Symantec in the Acknowledgements section.

rfc6962-bis.xml
So I can fix Ben's comments in Rob's absence.
=> Re-submission of PR 144: Ticket 156: New data structure for SCT + inclusion proof + STH.

rfc6962-bis.xml
[O] whether domains they are responsible for
[P] whether domains for which they are responsible
[R] grammar
Single very minor PR, will wait and confirm that the bot has been appeased before submitting more.
=> Minor grammar fix.

rfc6962-bis.xml
Add reference to metadata on first mention.
=> Reference to Metadata on first mention.

rfc6962-bis.xml
[O] Note that this is a general mechanism, but
[P] Note that this is a general mechanism; but
[R] Grammar/run on sentence
[O] of this document, but broadly speaking,
[P] of this document; but, broadly speaking,
[R] grammar/run on sentence
=> More grammar nits.

rfc6962-bis.xml
That section exists twice, remove it from the non-optional part.
=> Removing duplicate text.

rfc6962-bis.xml
Very much optional readability nit.
=> Section 5.3: Readability / flow.

rfc6962-bis.xml
See http://www.ietf.org/mail-archive/web/trans/current/msg02308.html
=> Addressing feedback from Steve Kent.

rfc6962-bis.xml
Addresses my comments on Sections 10.2.5 - 10.2.7: https://mailarchive.ietf.org/arch/msg/trans/mhQg2dYwygll-yStm9MbTCFxxt8
=> Clarify the role of the TLS feature extension

rfc6962-bis.xml
I'm sure it can be articulated in a better way.
=> First stab at simplifed redaction.

rfc6962-bis.xml
David Drysdale has provided detailed feedback on the -bis document.
This PR addresses most of the feedback.
=> Address Feedback from David Drysdale

draft-ietf-trans-rfc6962-bis.md
Addressing comments from Paul Wouters:
* Refer to an RFC for SHA-256.
* Name IANA registries.
=> Address comments about the IANA section

draft-ietf-trans-rfc6962-bis.md
Remove all references to name-constrained intermediates.
=> Remove the 'Private Domain Name Labels' section.

draft-ietf-trans-rfc6962-bis.md
Follow up to PR #239 , which lacked a proper reference and with another change requested by @robstradling .
=> Follow-up PR for dealing with BCP 190

draft-ietf-trans-rfc6962-bis.md
=> Remove remnants of TLS Feature support.

draft-ietf-trans-rfc6962-bis.md
=> PR256 follow-up

draft-ietf-trans-rfc6962-bis.md
=> A-D review: Various fixes in the IANA Considerations section

draft-ietf-trans-rfc6962-bis.md
=> A-D review: Provide a TLS 1.3 mapping.

draft-ietf-trans-rfc6962-bis.md
Change the error output format to be the Problem Details Object from
RFC7807.
Seems pretty straightforward given that the 6962-bis errors do not
have unique requirements and so can comply with said RFC.
=> Output errors in compliance with RFC7807

draft-ietf-trans-rfc6962-bis.md
Some wordsmithing following on from PR #300.
=> Clarify behaviour for malformed requests.

draft-ietf-trans-rfc6962-bis.md
Also ask IANA to create the trans:error registry.
Also tweak some markdown syntax so my vim coloring isn't a screen
full of yellow :)
=> Address Alexey DISCUSS items

CONTRIBUTING.md
=> Add IETF Contributing rules.

draft-ietf-trans-rfc6962-bis.md
This PR addresses Roman's comments.
=> Roman comments

draft-ietf-trans-rfc6962-bis.md
This addresses Alexey's comments that haven't already been resolved.
There is one open question about base64, posted to the list as https://mailarchive.ietf.org/arch/msg/trans/a0MXL0pqVRKi8NB8199YoUQRlpo/  Once I get confirmation I will take this out of WIP; commit 737b95fe09868811f86be01975649143c608edb2 has the expected wording.
=> Alexey comments

draft-ietf-trans-rfc6962-bis.md
=> Clarify "tree_size" and "requested STH" for proof endpoints

draft-ietf-trans-rfc6962-bis.md
Move RFC Editor note to Abstract.
=> Add ASN.1 module

draft-ietf-trans-rfc6962-bis.md
Add request for IANA OID assignment (requested by Russ).
Reformat TLS registry request to be tabular.
=> Iana oid request

draft-ietf-trans-rfc6962-bis.md
- Change Expert Review to Specification Required in one section
- Use requested OID in the ASN1 module
- Fix whitespace, add a comma
=> Ben Kaduk's final comments:

draft-ietf-trans-rfc6962-bis.md
Per discussion with Martin re his IESG comments.
=> Add ref to Private Enterprise Number page.
